apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: event-exporter
  name: event-exporter
  namespace: {{ default "kubestar" .Release.Namespace }}
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: event-exporter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        app: event-exporter
    spec:
      containers:
        - name: event-exporter
          image: {{ include "common.image" . }}
          imagePullPolicy: Always
          args:
            - --eventType=Warning
          ports:
            - containerPort: 8080
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: event-exporter
      terminationGracePeriodSeconds: 30
