apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: event-exporter
  name: event-exporter
  namespace: {{ default "kubestar-monitor" .Release.Namespace }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: event-exporter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '9102'
        prometheus.io/scrape: 'true'
      labels:
        app: event-exporter
    spec:
      containers:
        - name: event-exporter
          image: 'kubestar/event-exporter:v1.0.1'
          imagePullPolicy: Always
          args:
            - --eventType=Warning
          ports:
            - containerPort: 9102
              name: http
          resources:
            limits:
              memory: 100Mi
            requests:
              memory: 40Mi
      serviceAccountName: event-exporter
      terminationGracePeriodSeconds: 30
