apiVersion: v1
kind: Service
metadata:
  labels:
    app: event-exporter
  name: event-exporter
  namespace: {{ default "kubestar" .Release.Namespace }}
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 9102
      targetPort: 9102
  selector:
    app: event-exporter