apiVersion: v1
kind: Service
metadata:
  labels:
    app: event-exporter
  name: event-exporter
  namespace: {{ default "kubestar" .Release.Namespace }}
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: event-exporter