apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-exporter
  labels:
    app: event-exporter
  namespace: {{ default "kubestar-monitor" .Release.Namespace }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}