global:

image:
  repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
  tag: v2.6.0
  pullSecrets: []

resources:
  limits:
    cpu: 200m
    memory: 400Mi
  requests:
    cpu: 20m
    memory: 200Mi

annotations: {}

podAnnotations: {}