apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kube-state-metrics
  name: kube-state-metrics
  namespace: {{ default "kubestar" .Release.Namespace }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}