apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-exporter
  name: node-exporter
  namespace: {{ default "kubestar-monitor" .Release.Namespace }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  ports:
    - name: http
      port: 9100
      protocol: TCP
  type: ClusterIP
  selector:
    app: node-exporter