apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-exporter
  name: node-exporter
  namespace: kubestar-monitor
spec:
  ports:
    - name: http
      port: 9100
      protocol: TCP
  type: ClusterIP
  selector:
    app: node-exporter