kind: "DaemonSet"
apiVersion: "apps/v1"
metadata:
  name: "cadvisor"
  labels:
    app: "cadvisor"
  namespace: {{ default "kubestar-monitor" .Release.Namespace }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: "cadvisor"
  template:
    metadata:
      labels:
        app: "cadvisor"
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      containers:
        - name: "cadvisor"
          image: {{ include "common.image" . }}
          args:
            {{- toYaml .Values.containerArgs | nindent 12 }}
          ports:
            - name: "http"
              containerPort: 8080
              protocol: "TCP"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
