apiVersion: v1
kind: Service
metadata:
  labels:
    app: cadvisor
    name: cadvisor
  name: cadvisor
  namespace: kubestar-monitor
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: cadvisor
    name: cadvisor