{{- if .Values.prometheus.monitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: {{ .Values.prometheus.monitor.release }}
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
  name: {{ include "standard-cadvisor.fullname" . }}
  namespace: {{ default "kubestar" .Release.Namespace }}
spec:
  attachMetadata:
    node: false
  endpoints:
    - port: http
      scheme: http
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: cadvisor
{{- end }}

