{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: security-webhook
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
  name: security-webhook
  namespace: {{ .Release.Namespace }}
data:
  default.yaml: |
    checkItems:
      forbiddenPrivilegedContainer: {{ .Values.configmap.forbiddenPrivilegedContainer }}
{{- end }}