apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: security-webhook
  annotations:
      {{- include "common.annotations" . | nindent 4 }}
  name: security-webhook
spec:
  selector:
    matchLabels:
      app: security-webhook
  replicas: 1
  template:
    metadata:
      labels:
        app: security-webhook
    spec:
      containers:
        - name: security-webhook
          image: {{ include "common.image" . }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9443
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/certs/
              name: tls-cert
      volumes:
        - name: tls-cert
          secret:
            secretName: security-webhook-certificate-secret