apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: security-webhook-validate
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/security-webhook-certificate
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: ""
      service:
        name: security-webhook
        namespace: {{ .Release.Namespace }}
        port: 443
        path: /security-validate
    failurePolicy: Fail
    name: validate-privileged-container.{{ .Release.Namespace }}.svc
    namespaceSelector:
      matchExpressions:
        - key: "kubernetes.io/metadata.name"
          operator: NotIn
          values: ["kube-system"]
    rules:
      - apiGroups:
          - "apps"
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - deployments
          - statefulsets
          - daemonsets
        scope: '*'
    sideEffects: None
    timeoutSeconds: 3