global:

image:
  repository: prom/node-exporter
  tag: v1.6.0
  pullSecrets: []

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 20m
    memory: 100Mi



annotations: {}

podAnnotations: {}